title: Souradeep Das
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
aboutme: Undergraduate at Indian Institute of Science
navigationbar: true

markdown: kramdown
kramdown:
  math_engine: katex
